--- !ditz.rubyforge.org,2008-03-06/project 
name: Tofublox
version: "0.3"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: Tofublox
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Initial public release
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-06-17 20:29:38.546586 Z
    - Clinton R. Nixon <crnixon@gmail.com>
    - created
    - This should be the minimum of functionality for Tofu.
